config/routes.rb
Rails.application.routes.draw do
  root "games#new"
  resources :components
  resources :games
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/component.rb
class Component < ApplicationRecord
  belongs_to :game
  has_one_attached :image
end

app/models/game.rb
class Game < ApplicationRecord
  #has_one_attached :image
  has_many :rules
  has_many :components
  has_one_attached :avatar
  accepts_nested_attributes_for :components, allow_destroy: true
  accepts_nested_attributes_for :rules, allow_destroy: true
end

app/models/rule.rb
class Rule < ApplicationRecord
  has_one_attached :document
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/components_controller.rb
class ComponentsController < ApplicationController
  before_action :set_component, only: [:show, :edit, :update, :destroy]

  # GET /components
  # GET /components.json
  def index
    @components = Component.all
  end

  # GET /components/1
  # GET /components/1.json
  def show
  end

  # GET /components/new
  def new
    @component = Component.new
  end

  # GET /components/1/edit
  def edit
  end

  # POST /components
  # POST /components.json
  def create
    @component = Component.new(component_params)

    respond_to do |format|
      if @component.save
        format.html { redirect_to @component, notice: 'Component was successfully created.' }
        format.json { render :show, status: :created, location: @component }
      else
        format.html { render :new }
        format.json { render json: @component.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /components/1
  # PATCH/PUT /components/1.json
  def update
    respond_to do |format|
      if @component.update(component_params)
        format.html { redirect_to @component, notice: 'Component was successfully updated.' }
        format.json { render :show, status: :ok, location: @component }
      else
        format.html { render :edit }
        format.json { render json: @component.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /components/1
  # DELETE /components/1.json
  def destroy
    @component.destroy
    respond_to do |format|
      format.html { redirect_to components_url, notice: 'Component was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_component
      @component = Component.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def component_params
      params.require(:component).permit(:name, :quantity, :game_id)
    end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: [:show, :edit, :update, :destroy]

  # GET /games
  # GET /games.json
  def index
    @games = Game.all
  end

  # GET /games/1
  # GET /games/1.json
  def show
    @components = @game.components
    @rules = @game.rules
  end

  # GET /games/new
  def new
    @game = Game.new
  end

  # GET /games/1/edit
  def edit
  end

  # POST /games
  # POST /games.json
  def create
    @game = Game.new(game_params)

    respond_to do |format|
      if @game.save
        format.html { redirect_to @game, notice: 'Game was successfully created.' }
        format.json { render :show, status: :created, location: @game }
      else
        format.html { render :new }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /games/1
  # PATCH/PUT /games/1.json
  def update
    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to @game, notice: 'Game was successfully updated.' }
        format.json { render :show, status: :ok, location: @game }
      else
        format.html { render :edit }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    @game.destroy
    respond_to do |format|
      format.html { redirect_to games_url, notice: 'Game was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = Game.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def game_params

      params.require(:game).permit(:name, :description, :avatar, :max_players, :min_players, rules_attributes: [:name, :document],
      components_attributes: [:name, :image])    
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/components_helper.rb
module ComponentsHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/_component_detail.html.erb
<li class="media">
  <% if component.image.attached? %>
    <%= image_tag component&.image.variant(resize: "100x100").processed, class: "mr-3" %>
  <% end %>
    <div class="media-body">
      <h5 class="mt-0 mb-1"><%= component.name %></h5>
    </div>

    <% if component.image.attached? %>
      <%= link_to raw('<i class="fa fa-edit"></i>'), edit_game_path(component), class: "btn btn-info ml-2" %>

      <%= link_to raw('<i class="fa fa-download"></i>'), rails_blob_path(component.image, disposition: 'attachment'), class: "btn btn-warning" %>
    <% end %>
    </li>

app/views/games/_component_fields.html.erb
<div class="nested-fields">
  <div class="form-group">
    <%= f.text_field :name, class: "form-control", placeholder:'Nombre' %>
  </div>

  <div class="form-group">
    <%= f.number_field :quantity, class: "form-control", placeholder: 'Cantidad' %>
  </div>

  <div class="form-group">
    <div class="custom-file">
      <%= f.file_field :image, class: "custom-file-input" %>
      <%= f.label 'Escoge una imagen', class: "custom-file-label" %>
    </div>
  </div>


  <%= link_to_remove_association "Eliminar", f %>
</div>

app/views/games/_form.html.erb
<%= form_with(model: game, local: true) do |form| %>
  <% if game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
      <% game.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.text_field :name, class: "form-control", placeholder: "Nombre" %>
  </div>

  <div class="form-group">
    <%= form.text_area :description, class: "form-control", placeholder: "Descripción" %>
  </div>

  <div class="form-group">
      <div class="custom-file">
        <%= form.file_field :avatar, class: "custom-file-input" %>
        <%= form.label 'Escoge una portada', class: "custom-file-label" %>
      </div>
  </div>
  

  <div class="form-group">
    <%= form.text_field :max_players, class: "form-control", placeholder: "Máx. jugadores" %>
  </div>

  <div class="form-group">
    <%= form.text_field :min_players, class: "form-control", placeholder: "Min. jugadores" %>
  </div>

  <h3>Reglas</h3>
  <div class="field" id="rules">
    <%= form.fields_for :rules do |rule_form| %>
      <%= render 'rule_fields', f: rule_form %>
    <% end %>
    <div class="links">
      <%= link_to_add_association raw('<span><i class="fa fa-plus"></i>Regla</span>'), form, :rules, class: "btn btn-success" %>
    </div>
  </div>
  <br>

	<h3>Componentes</h3>
  <div class="field" id="components">
    <%= form.fields_for :components do |component_form| %>
      <%= render 'component_fields', f: component_form %>
    <% end %>
    <div class="links">
      <%= link_to_add_association raw('<span><i class="fa fa-plus"></i>Componente</span>'), form, :components, class: "btn btn-success" %>
    </div>
  </div>
  <br>

  <div class="actions">
    <%= form.submit 'Guardar', class: "btn btn-primary", class: "btn btn-success" %>
  </div>
  <br>
<% end %>

app/views/games/_rule_detail.html.erb
<li class="media">
    <%= document.name %>
    <div class="media-body">
      <h5 class="mt-0 mb-1"><%= document.name %></h5>
    </div>
    <%= link_to raw('<i class="fa fa-edit"></i>'), edit_game_path(document), class: "btn btn-info ml-2" %>
    <%= link_to raw('<i class="fa fa-download"></i>'), rails_blob_path(document.document, disposition: 'attachment'), class: "btn btn-warning" %>
  </li>

app/views/games/_rule_fields.html.erb
<div class="nested-fields">
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control", placeholder: "Nombre" %>
  </div>
<br>
  <div class="form-group">
    <div class="custom-file">
      <%= f.file_field :document, class: "custom-file-input" %>
      <%= f.label 'Escoge un documento', class: "custom-file-label" %>
    </div>
  </div>

  <%= link_to_remove_association "Eliminar", f %>
</div>

app/views/games/edit.html.erb
<h1>Editing Game</h1>

<%= render 'form', game: @game %>

<%= link_to 'Show', @game %> |
<%= link_to 'Back', games_path %>

app/views/games/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Games</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Min players</th>
      <th>Max players</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @games.each do |game| %>
      <tr>
        <td><%= game.name %></td>
        <td><%= game.min_players %></td>
        <td><%= game.max_players %></td>
        <td><%= game.description %></td>
        <td><%= link_to 'Show', game %></td>
        <td><%= link_to 'Edit', edit_game_path(game) %></td>
        <td><%= link_to 'Destroy', game, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Game', new_game_path %>

app/views/games/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-6 offset-3">

      <h1>Crear Juego</h1>

      <%= render 'form', game: @game %>

      <%= link_to 'Back', games_path %>
    </div>
  </div>
</div>

app/views/games/show.html.erb
<div class="container">
  <div class="row mt-2">
    <div class="col-2 offset-10 text-right">
      <%= link_to 'Back', games_path, class: "btn btn-secondary btn-block" %>
    </div>
  </div>
  <div class="row mt-2">
    <div class="col-4">
      <div class="card" style="width: 18rem;">
        <%= image_tag @game.avatar%>
        <div class="card-body">
          <h5 class="card-title"><%= @game.name %></h5>
          <p class="card-text"><%= @game.description %></p>
        </div>
        <div class="card-footer">
          <%= link_to raw('<i class="fa fa-edit"></i>'), edit_game_path(@game), class: "btn btn-info" %>
          <%= link_to raw('<i class="fa fa-download"></i>'), edit_game_path(@game), class: "btn btn-warning" %>
        </div>
      </div>
    </div>
    <div class="col-4">
      <% @components.each do |component| %>
        <ul class="list-unstyled">
          <%= render 'component_detail', component: component%>
        </ul>
      <% end %>
      <% @rules.each do |document| %>
        <ul class="list-unstyled">
          <%= render 'rule_detail', document: document %>
        </ul>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Games</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  
  <body>
  <%= render "shared/navbar" %>
    <%= yield %>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
  </body>
</html>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <%= link_to 'Juegos', games_path, class: "nav-link"%>
      </li>
    </ul>
  </div>
</nav>